### ISSUE TITLE
字在屏幕边框处被分割成一半，右边框一半左边框一半

### ISSUE THREAD

**Issue by detiam** [zhmars/cjktty-patches#1]
网络原因无法上传图片所以没有截图，但真的有这个问题。
当中文文字单行数量多出屏幕宽度且一行内有奇数数量的半角字符时。

**Comment by zhmars** [comment]
不好意思，现在才回复

刚测试，确实有这个问题，建议向[原作者](https://github.com/Gentoo-zh/linux-cjktty)反馈

**Comment by zhmars** [comment]
我尝试在 5.10 修复这个问题，有兴趣的话可以试试。
