### ISSUE TITLE
kernel 5.10.186 console不能显示中文

### ISSUE THREAD

**Issue by gengw2000** [zhmars/cjktty-patches#10]
我的kernel从5.10.46升级到5.10.186后，console就不能显示中文了。kernel的config项我都逐项比对过了没有发现异常。这是相关的kernel配置项：
```
CONFIG_FONTS=y
 # CONFIG_FONT_10x18 is not set
 # CONFIG_FONT_6x10 is not set
 # CONFIG_FONT_6x11 is not set
 # CONFIG_FONT_7x14 is not set
CONFIG_FONT_8x16=y
CONFIG_FONT_8x8=y
# CONFIG_FONT_ACORN_8x8 is not set
CONFIG_FONT_CJK_16x16=y
CONFIG_FONT_CJK_32x32=y
# CONFIG_FONT_MINI_4x6 is not set
# CONFIG_FONT_PEARL_8x8 is not set
# CONFIG_FONT_SUN12x22 is not set
# CONFIG_FONT_SUN8x16 is not set
CONFIG_FONT_SUPPORT=y
CONFIG_FRAMEBUFFER_CONSOLE=y
CONFIG_FRAMEBUFFER_CONSOLE_DEFERRED_TAKEOVER=y
CONFIG_FRAMEBUFFER_CONSOLE_DETECT_PRIMARY=y
CONFIG_FRAMEBUFFER_CONSOLE_LEGACY_ACCELERATION=y
CONFIG_FRAMEBUFFER_CONSOLE_ROTATION=y
CONFIG_FRAME_POINTER=y
```

请大佬拨冗指导。另外我用kernel 5.15测试过也不能显示中文。

**Comment by gengw2000** [comment]
还有两点疑惑：
1). 5.10版本的kernel需要安装cjktty-add-cjk32x32-font-data.patch吗？我安装的是cjktty-5.10.patch
2). 在5.10.46的kernel config中有CONFIG_FONT_16x16_CJK=y这个配置项。但是在5.10.186中没有这个配置项了，不知道是不是这个原因？

**Comment by zhmars** [comment]
`不能显示中文` 具体是啥情况，最好截个图看看

> 1). 5.10版本的kernel需要安装cjktty-add-cjk32x32-font-data.patch吗？我安装的是cjktty-5.10.patch

默认的字体在高分屏显示下很小，如果想要大字体就需要（包括 5.10 之后的所有版本）

> 2). 在5.10.46的kernel config中有CONFIG_FONT_16x16_CJK=y这个配置项。但是在5.10.186中没有这个配置项了，不知道是不是这个原因？

看 README，这个选项在  5.10 改名成 `CONFIG_FONT_CJK_16x16`，能找到这个选项说明原来用的不是 5.10 的补丁

**Comment by gengw2000** [comment]
![QQ截图20230718144223](https://github.com/zhmars/cjktty-patches/assets/3714857/914a9851-51fd-413e-b223-c9038d88aeb5)
汉字显示的都是小方块

**Comment by gengw2000** [comment]
5.10安装不了cjktty-add-cjk32x32-font-data.patch这个补丁吧？提示Patch failed。

**Comment by gengw2000** [comment]
我又重新检查了一下。CONFIG_FONT_16x16_CJK这个选项是我手动加上去的，之前的kernel 5.10.46版本也不需要CONFIG_FONT_16x16_CJK就可以正常显示中文。现在5.10.46的kernel config和5.10.186完全一样了，但是5.10.186就是不能显示中文。

**Comment by gengw2000** [comment]
再更新一下：

现在新发现只有vmware虚拟机里面不能显示中文，物理机是可以正常显示的。这又是什么原因呢？是需要额外的驱动吗？

**Comment by zhmars** [comment]
> 5.10安装不了cjktty-add-cjk32x32-font-data.patch这个补丁吧？提示Patch failed。

5.10  是 20 年发布的版本，还想用的话就用旧的补丁，那时还不叫这个名字，它在这：https://github.com/zhmars/cjktty-patches/tree/0acfa3fdfe900ad15e56b513be70061f86cfe606/font

> 现在新发现只有vmware虚拟机里面不能显示中文，物理机是可以正常显示的。这又是什么原因呢？是需要额外的驱动吗？

不知道，我现在不是很理解你前后说的话。如果内核有开启 `CONFIG_IKCONFIG_PROC`，检查下虚拟机和物理机的输出是不是以下这样：

```sh
$ zgrep CJK /proc/config.gz
CONFIG_FONT_CJK_16x16=y
CONFIG_FONT_CJK_32x32=y
```

**Comment by gengw2000** [comment]
我的意思是用物理机可以显示中文，vmware虚拟机的console里面的中文显示不了。

**Comment by gengw2000** [comment]
安装了cjktty-add-uni32x32-font-data.patch这个补丁也不行，显示还是和上面截图的一样。

**Comment by gengw2000** [comment]
![QQ截图20230720105250](https://github.com/zhmars/cjktty-patches/assets/3714857/d9f59d17-b22e-49e1-be01-44adc1c16e76)

/proc/config.gz里面是包含CJK选项的。

**Comment by gengw2000** [comment]
已解决，应该是vmware的framebuffer缺少驱动导致的，把这两个配置项启用了就可以正常显示：
CONFIG_DRM_VMWGFX=y
CONFIG_DRM_VMWGFX_FBCON=y

**Comment by sdir** [comment]
> 再更新一下：
> 
> 现在新发现只有vmware虚拟机里面不能显示中文，物理机是可以正常显示的。这又是什么原因呢？是需要额外的驱动吗？

方便细说一下，物理机后来是启用了什么配置后可以正常显示的吗？目前我也是使用的5.10的内核，在物理机上BIOS为 legacy模式下无法正常显示，而使用UEFI模式启动可以。

**Comment by gengw2000** [comment]
物理机一直都可以，不需要启用额外的配置
