### ISSUE TITLE
6.4.x在6.4.11内核上补丁报错。

### ISSUE THREAD

**Issue by harvey-git** [zhmars/cjktty-patches#11]
补丁报错见下图：
![2023-08-23 15-32-40屏幕截图](https://github.com/zhmars/cjktty-patches/assets/52305566/ad27f619-4dc1-4e66-b6e9-b72ce78160e9)

报错后强行编译失败，见下图：

![2023-08-23 15-34-48屏幕截图](https://github.com/zhmars/cjktty-patches/assets/52305566/06b5c819-cc9c-44af-a9f8-72548bdd3889)

**Comment by zhmars** [comment]
> The next patch would create the file lib/fonts/font_cjk_16x16.c,
which already exists!  Skipping patch.
1 out of 1 hunk ignored

重复打了补丁吗？这个文件是补丁新增的，这里提示已存在，如果目录干净的话，不可能有这提示。

**Comment by harvey-git** [comment]
> > 下一个补丁将创建文件 lib/fonts/font_cjk_16x16.c，
> > 该文件已经存在！跳过补丁。
> > 十分之一的大块头被忽略
> 
> 打了补丁吗？这个文件是补丁新增的，这里提示已存在，如果目录干净重复的话，不可能有这个提示。
我记得是没有打补丁的，第一次应用，不管了，我删除了整个目录，重新下载解压内核源码，再次重新应用补丁，果然没有报错了，谢谢
