### ISSUE TITLE
编译时选择cjk font后依旧不能显示中文

### ISSUE THREAD

**Issue by Freed-Wu** [zhmars/cjktty-patches#2]
![2020-02-19 15-33-35 的屏幕截图](https://user-images.githubusercontent.com/32936898/74811884-674db100-532d-11ea-9838-b2ecc755b70d.png)

选择该选项后编译后中文依旧显示实心方块。请问是还要选择其他选项吗？谢谢！

**Comment by zhmars** [comment]
选择该选项即可，记得保存。建议先检查内核配置文件是否有 `CONFIG_FONT_16x16_CJK=y`

**Comment by zhmars** [comment]
无回复，关了哈（有问题可以再开）

**Comment by Freed-Wu** [comment]
在`/etc/kernels/kernel-config-5.4.13-gentoo-x86_64`中添加了`CONFIG_FONT_16x16_CJK=y`后成功了，非常感谢！

**Comment by Freed-Wu** [comment]
![IMG20200225121003](https://user-images.githubusercontent.com/32936898/75214649-3657fb00-57c9-11ea-9216-23645a78c774.jpg)

一个小问题，图中英文是黑底白字，中文变成了白底黑字，有什么办法可以统一一下吗？

谢谢！

**Comment by zhmars** [comment]
换个主题试试？

如果我理解没错，这个问题应该与补丁无关，一般都是黑底白字。
