### ISSUE TITLE
怎么在运行时选择字体呢？

### ISSUE THREAD

**Issue by lilydjwg** [zhmars/cjktty-patches#3]
比如我想要 CJK32x32 字体，但是目前是 CJK16x16 字体。

我知道可以通过内核参数 `fbcon=font:xxx` 来指定。可是一开始没指定好的话就得重启。我总不能接个显示器就要重启一次，然后拔了显示器再重启一次吧……

**Comment by zhmars** [comment]
4K 屏的话开机应该能自动选择 32x32 的字体（假设已经打了字体数据补丁，没有实测过，因为没有 4K 屏）

内置字体的指定，我了解到的只有你说的这种方式，临时需要的话可以试试`setfont`。
