### ISSUE TITLE
有简单的教程么？

### ISSUE THREAD

**Issue by pisingtoog** [zhmars/cjktty-patches#4]
linux新手一个。
使用命令：patch -Np1 < **.patch； 提示让选择file to patch ，输入绝对地址，就提示，file not found

**Comment by 12101111** [comment]
最简单的就是用git管理linux源码

```
git clone https://mirrors.ustc.edu.cn/linux.git
git apply xxx.patch
git commit
```

然后有新更新了

```
git fetch origin
git merge origin/v5.11.8
```

或者直接`git pull`

**Comment by zhmars** [comment]
> 提示让选择file to patch ，输入绝对地址，就提示，file not found

可能目录不对，打补丁前注意先切换到 **Linux 源码根目录**。


如果熟悉 git 也可以试试 @12101111 的方法，但同样要注意 `git clone` 后切换目录（`cd linux`）再打补丁。
