### ISSUE TITLE
能以dkms的形式安装到内核吗？

### ISSUE THREAD

**Issue by chinese-wzq** [zhmars/cjktty-patches#7]
我对这方面的了解并不够深，我只是看到许多能在编译内核时添加参数的模块都能以dkms的形式安装到系统上，所以我想知道cjktty能不能也转换成支持dkms的形式呢？（这样可以减少安装别的内核后可能造成的一系列问题，比如安装nvidia驱动就还需要安装nvidia-dkms）。我的系统是Arch Linux，在包管理器里面已经有了包含cjktty的内核，但就是没有cjktty-dkms之类的东西。

**Comment by zhmars** [comment]
不能，DKMS 确实很方便，但并不是所有驱动都能以编译成模块加载。
