### ISSUE TITLE
显示中文为麻麻点点的方块

### ISSUE THREAD

**Issue by aqssxlzc** [zhmars/cjktty-patches#9]
内核为6.2.6
![IMG_20230317_014227](https://user-images.githubusercontent.com/1112573/225797391-7b5cc00c-3a81-49a8-8bea-674a48482e61.jpg)
内核编译配置也打开了
![IMG_20230317_014420](https://user-images.githubusercontent.com/1112573/225797434-51d7484e-d88d-45f8-8560-9996e8d45440.jpg)

**Comment by zhmars** [comment]
> To have a larger font on high resolution screens, you probably want to apply 32x32 font data patch.

大字体需要加上 `cjktty-add-cjk32x32-font-data.patch`
